name: 🐞 Premium Bug report
description: Report a bug in Enchant-Boost Premium Version.
title: "[BUG] Your Title Here"
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to report an Enchant Boost bug! Fill out the form below to provide us with info to help fix the bug.
      Only use this if you're 100% sure you've found a bug and can reproduce it. If you're looking for general help with Enchant Boost, try the Discord server.

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: dropdown
  attributes:
    label: Type of bug
    description: What type of bug is this? Choose ALL that apply.
    multiple: true
    options:
      - Performance issue or memory leak
      - Data loss
      - Exploit
      - Compatibility issue
      - Error in console
      - Config Error
      - In Game Functionality
      - Lore Issues
      - Sound Effect Issues
      - Other unexpected behaviour
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Server Version**: Paper 1.21
        - **Enchant-Boost Version**: 1.21.0
    value: |
        - Server Version: 
        - Enchant-Boost Version: 
    render: markdown
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      Please make sure you are **NOT** using Hastebin, or any other self-hosted clone of Hastebin, as by default they will be deleted after 24 hours.
      *We will not be able to assist you if your pastes have been deleted before being seen.*

- type: input
  attributes:
    label: Server startup log
    description: Upload your server startup log (from the start of `latest.log` up to where it says "Done!").
  validations:
    required: true

- type: input
  attributes:
    label: EnchantBoost Config File
    description: Upload your Shop `config.yml` (and any other relevant files like `displayConfig.yml`).
  validations:
    required: true

- type: input
  attributes:
    label: Error log (if applicable)
    description: If you are reporting a console error, upload any relevant log excerpts.

- type: textarea
  attributes:
    label: Bug description
    description: Describe roughly what the bug is here.
    placeholder: |
      Example: "Enchantment did not work."
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Provide an example of how to trigger the bug.
    placeholder: |
      Example:
      1. Place item in slot 1.
      2. Place book in slot 2.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: Explain what you should expect to happen.
    placeholder: |
      Example: "Players should receive an item."
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behaviour
    description: Explain what actually happens.
    placeholder: |
      Example: "Players don't see the result item."
  validations:
    required: true

- type: textarea
  attributes:
    label: Other information
    description: |
      In the text box below, you can attach any relevant screenshots, videos, files, and links to Timings/spark profiler reports.
      You can also include a link to a heapdump if necessary, but please make sure you don't include any private player data in the heapdump.
      If you suspect this issue is related to a prior issue/PR/commit, please mention it here.
    placeholder: |
      examples:
        - https://timings.aikar.co/?id=16fa8c9919a74f6d9724afc9697aa4de
        - https://spark.lucko.me/2HjwNC9UOv
  validations:
    required: false
